### ISSUE TITLE
First time: Creating a new account HANGS, then NEVER shows the user account cert id created in the top bar, even after REFRESH...

### ISSUE THREAD

**Issue by haschimoto** [zer0net/zerovoat#162]
![snap 2018-05-03 at 21 15 10](https://user-images.githubusercontent.com/20817185/39597915-353a836c-4f17-11e8-90d8-a6e42a771cd8.png)

clicking "New Topic" shows this:
![snap 2018-05-03 at 21 16 40](https://user-images.githubusercontent.com/20817185/39597960-57161c6c-4f17-11e8-8058-69c6c26f9718.png)

These two bugs affecting new CERTS/Accounts are absolute critical for IFS and ZV, since no new users can create any IFS/ZV cert accounts...

**Comment by dnelband** [comment]
Hi, yes, you're totally right, it shouldn't be like that. i've tested it now, i still havent isolated the problem yet, but i suspect it has sth to do with the geocities db download that every new client does in the beginning, in which case we need some kind of checking procedures to see if its user has everything installed. in any case im gonna test it more and update

**Comment by haschimoto** [comment]
Yeah, that could be true.
I also will test things again.

**Comment by haschimoto** [comment]
has nothing to do with geocities DB...
geocities has been fully loaded before going to ZV.
it is ZV related.
It takes about 2 minutes, everything else has long completely loaded, so whole zite is perfectly browsable already.

Even a browser frefresh does not stop the IDLE time...

@dnelband : this has absolutely priority, it prevents completely new users from trying out the platform.

**Comment by haschimoto** [comment]
this happens WHENEVER you log out and then simply refresh a page...

**Comment by haschimoto** [comment]
to stop it, one can go to any topic, then hit blue "LOGIN" button next to the comment field to popup the CERT chooser, then select ZV anon cert id, then it is stuck you simply REFRESH the page, then you see login cert at top.

Now after that you simply select "switch" and select no certification again to logout, then it is stuck again even after refresh page... so it never works or falls back in non-logged in state...

**Comment by dnelband** [comment]
what i could able to reproduce:
- fresh install
- load ZeroVoat, initial screen asks for permissions & add merger sites
- while ZeroVoat loads the merger sites files (i.e when the green bar is going crazy on initial load) it seems to queue the function to register user
- even after loading all the files, the ZeroVoat API doesnt reach the user's data.json file
- only after dragging the zero icon and getting the notification that "zeronet is downloading geocities" & refresh does the ZeroNet API manage to fetch the data.json file, and register the user
- here there was another bug which created an endless loading loop, now i've fixed it (just updated so it may take a few minutes)

so it seems that while ZeroNet is initializing all the basic plugins, loading & creating user files is queued or timed out. 

temporary solution:
with the initial load of ZeroVoat, display an info message like "if this is a fresh ZeroNet install, please wait for a few minutes until ZeroNet installs all the relevant plugins, before you register" until i figure a way out to prevent bugs at that stage

**Comment by haschimoto** [comment]
but it was not like that before and also seems fixed now for the endless loop.
I dont think we need anything special than any other zite for new users, it was that internal bug and now it seems solved.

**Comment by haschimoto** [comment]
its not solved.
easily provable by going to e.g. this proxy and seeing the spinning circle never finishes:
https://www.zerogate.tk/1J1c7eML6uMwDU4uiKbKRxoqxGP6WMFMvb/

People new  first time on ZV will be opening ZV, give up and move on.

**Comment by haschimoto** [comment]
this is what is executed and created the absolute first time visiting ZV:
![snap 2018-06-02 at 16 56 36](https://user-images.githubusercontent.com/20817185/40877729-0710c470-6686-11e8-9000-1a9da6dbb82f.png)

**Comment by haschimoto** [comment]
after 10 minutes, it showed this after refresh:
![snap 2018-06-02 at 17 34 13](https://user-images.githubusercontent.com/20817185/40878045-585a20a6-668b-11e8-8d70-e2e46172ff2c.png)

If selecting Yes, it showed this:
![snap 2018-06-02 at 17 34 24](https://user-images.githubusercontent.com/20817185/40878047-6201ad86-668b-11e8-92ec-c8842e58bee1.png)

Then after another PAGE refresh, it said "user content json patched" and finally showed the user:
![snap 2018-06-02 at 17 36 24](https://user-images.githubusercontent.com/20817185/40878050-819fa652-668b-11e8-8e63-eb36c54d3879.png)

**Comment by dnelband** [comment]
ok i've tested it on a local client & zerogate.tk - on local the first time registration etc' runs as expected, but on zerogate.tk it "loads forever", while debugging this i see that it hangs on the ZeroAPI request to get the user's data from the data.json, so on zerogate.tk there is a lag with the server or sth it seems. also notice that the font isnt loaded. regardless, im still trying to see how to fix it but i believe that the problem doesnt reproduce itself on every client.

**Comment by haschimoto** [comment]
It is not fixed.
Fresh local ZN, then loading ZV the firs time the cert gets created and the user asked to select an ID...
Maybe we should not AUTO-ask the user to login the first time, but leave the login button at the top, so people can manually click on the login button and then get presented the certs again?

**Comment by haschimoto** [comment]
so first time loading is:
- grant merger type
- grant merger sites
- generate cert
- NOT asking for login, but leave as is, so end result is this:
![snap 2018-06-28 at 21 55 00](https://user-images.githubusercontent.com/20817185/42057605-2de8d37e-7b1e-11e8-8912-cb65ea2e98ec.png)
then if pressed login, it looks like this:
![snap 2018-06-28 at 21 55 21](https://user-images.githubusercontent.com/20817185/42057615-364eb27c-7b1e-11e8-8b0d-391ee647587d.png)
then if selected, it sign and publish user:
![snap 2018-06-02 at 17 34 24](https://user-images.githubusercontent.com/20817185/40878047-6201ad86-668b-11e8-92ec-c8842e58bee1.png)
